<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[3]=array(0,1,1,'5ama57qx5bGV56S6');
$cfg_Cs[4]=array(0,1,1,'5paw5aiY6YCg5Z6L');
$cfg_Cs[5]=array(0,1,1,'56S85pyN5bGV56S6');
$cfg_Cs[6]=array(0,1,1,'5LyY56eA5qGI5L6L');
$cfg_Cs[7]=array(0,1,1,'55WZ6KiA5Y+N6aaI');
$cfg_Cs[8]=array(0,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[9]=array(0,1,1,'6IGU57O75oiR5Lus');
?>