<li><a href="[field:arcurl/]" title="[field:title/]">
        <div class="time"><span>[field:pubdate function="MyDate('m-d',@me)"/]</span><font>[field:pubdate function="MyDate('Y',@me)"/]</font></div>
        <div class="newsli_r">
          <p class="newsli_rt"><span class="fl">[field:title/]</span></p>
          <em>点击量：[field:click/]</em>
          <p>[field:description function="cn_substr(@me,255)"/]...</p>
        </div>
        </a>
	  </li>