<li>
    <div class="pro_li_img"> <a href="[field:arcurl/]" title="[field:title/]"><img  src="[field:picname/]" width="208" height="278" alt="[field:title/]"></a></div>
    <div class="pro_li_txt">
      <p class="pro_txtimg_t"><a href="[field:arcurl/]" title="[field:title/]" class="fl">
      [field:title/]</a> <a href="[field:arcurl/]"  class="viewmore" title="查看更多">查看更多</a> </p>
      <p class="">[field:description function="cn_substr(@me,255)"/]...</p>
    </div>
</li>