<?php
$z[0]=Array("include","",2235,2270);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",2336,2358);
$z[1][4]['name']="typename";
$z[2]=Array("field","",2407,2436);
$z[2][4]['name']="position";
$z[3]=Array("field","",2751,2770);
$z[3][4]['name']="title";
$z[4]=Array("field","",2823,2879);
$z[4][4]['name']="pubdate";
$z[4][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[5]=Array("field","",2912,2932);
$z[5][4]['name']="writer";
$z[6]=Array("field","",2981,3008);
$z[6][4]['name']="phpurl";
$z[7]=Array("field","",3032,3055);
$z[7][4]['name']="id";
$z[8]=Array("field","",3060,3084);
$z[8][4]['name']="mid";
$z[9]=Array("field","",3218,3236);
$z[9][4]['name']="body";
$z[10]=Array("include","",3673,3710);
$z[10][4]['filename']="footer.htm";

?>