<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",344,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",412,471);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2044,2079);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",2145,2167);
$z[5][4]['name']="typename";
$z[6]=Array("field","",2216,2245);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n<li>\r\n    <div class=\"pro_li_img\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img  src=\"[field:picname/]\" width=\"208\" height=\"278\" alt=\"[field:title/]\"></a></div>\r\n    <div class=\"pro_li_txt\">\r\n      <p class=\"pro_txtimg_t\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"fl\">\r\n      [field:title/]</a> <a href=\"[field:arcurl/]\"  class=\"viewmore\" title=\"查看更多\">查看更多</a> </p>\r\n      <p class=\"\">[field:description function=\"cn_substr(@me,255)\"/]...</p>\r\n    </div>\r\n</li>\r\n",2506,3047);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",3078,3155);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="3";
$z[9]=Array("include","",3525,3562);
$z[9][4]['filename']="footer.htm";

?>