<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",344,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",412,471);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2044,2079);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",2145,2167);
$z[5][4]['name']="typename";
$z[6]=Array("field","",2216,2245);
$z[6][4]['name']="position";
$z[7]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n",2356,2482);
$z[7][4]['type']="son";
$z[8]=Array("list","\r\n<li> \r\n	<a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" width=\"240\" height=\"320\" alt=\"[field:title/]\"></a> <a title=\"[field:title/]\" href=\"[field:arcurl/]\" class=\"protxt\">\r\n    [field:title/]</a>\r\n</li>\r\n",2621,2893);
$z[8][4]['pagesize']="6";
$z[9]=Array("pagelist","",2927,3004);
$z[9][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[9][4]['listsize']="3";
$z[10]=Array("include","",3372,3409);
$z[10][4]['filename']="footer.htm";

?>